<link rel="stylesheet" href="{{asset('public/frontend-assets/assets/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('public/frontend-assets/assets/css/animate.min.css')}}">
<link rel="stylesheet" href="{{asset('public/frontend-assets/assets/css/magnific-popup.css')}}">
<link rel="stylesheet" href="{{asset('public/frontend-assets/assets/css/fontawesome-all.min.css')}}">
<link rel="stylesheet" href="{{asset('public/frontend-assets/assets/css/jquery.mCustomScrollbar.min.css')}}">
<link rel="stylesheet" href="{{asset('public/frontend-assets/assets/css/bootstrap-datepicker.min.css')}}">
<link rel="stylesheet" href="{{asset('public/frontend-assets/assets/css/swiper-bundle.min.css')}}">
<link rel="stylesheet" href="{{asset('public/frontend-assets/assets/css/jquery-ui.min.css')}}">
<link rel="stylesheet" href="{{asset('public/frontend-assets/assets/css/nice-select.css')}}">
<link rel="stylesheet" href="{{asset('public/frontend-assets/assets/css/jarallax.css')}}">
<link rel="stylesheet" href="{{asset('public/frontend-assets/assets/css/flaticon.css')}}">
<link rel="stylesheet" href="{{asset('public/frontend-assets/assets/css/slick.css')}}">
<link rel="stylesheet" href="{{asset('public/frontend-assets/assets/css/default.css')}}">
<link rel="stylesheet" href="{{asset('public/frontend-assets/assets/css/style.css')}}">
<link rel="stylesheet" href="{{asset('public/frontend-assets/assets/css/responsive.css')}}">